using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 

[WebService(Namespace = "http://www.msn.com/webservices/Messenger/Client", Name = "AppDirectory", Description = "Returns data about individual P4 apps or P4 app categories")]
[WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Web.Services.WebServiceBindingAttribute(Name = "AppDirectorySoap", Namespace = "http://www.msn.com/webservices/Messenger/Client")]
public class AppDirectory : System.Web.Services.WebService
{

    /// <remarks/>
    public AppDirectory()
    {
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/Messenger/Client/GetAppEntry", RequestNamespace = "http://www.msn.com/webservices/Messenger/Client", ResponseNamespace = "http://www.msn.com/webservices/Messenger/Client", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [WebMethod]
    public Entry GetAppEntry(int ID)
    {
        //object[] results = this.Invoke("GetAppEntry", new object[] {
        //            ID});
        ID = 10;
        object[] results = new object[] { ID };

        return ((Entry)(results[0]));
    }
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/Messenger/Client/GetFullDataSet", RequestNamespace = "http://www.msn.com/webservices/Messenger/Client", ResponseNamespace = "http://www.msn.com/webservices/Messenger/Client", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [WebMethod]
    public System.Data.DataSet GetFullDataSet()
    {
        DataTable table1 = new DataTable("Entry");
        //table1.Columns.Add("name");
        //table1.Columns.Add("id");
        //table1.Rows.Add("sam", 1);

        //table1.Rows.Add("mark", 2);

        table1.Columns.Add("EntryID"); // 7
        table1.Columns.Add("Error"); //
        table1.Columns.Add("Locale"); //en-us
        table1.Columns.Add("Kids"); // 1
        table1.Columns.Add("Page"); // 1
        table1.Columns.Add("Category"); // 50
        table1.Columns.Add("Sequence"); // 10
        table1.Columns.Add("Name"); //File Sharing
        table1.Columns.Add("Description"); //Share Files Between Two Users!
        table1.Columns.Add("URL"); //http://appdirectory.messenger.msn.com/snake/index.html
        table1.Columns.Add("IconURL"); //
        table1.Columns.Add("PassportSiteID"); // 0
        table1.Columns.Add("Type"); //App
        table1.Columns.Add("Height"); //500
        table1.Columns.Add("Width"); //500
        table1.Columns.Add("Location"); //side
        table1.Columns.Add("MinUsers"); // 2
        table1.Columns.Add("MaxUsers"); // 2
        table1.Columns.Add("EnableIP"); //False
        table1.Columns.Add("ActiveX"); //True
        table1.Columns.Add("SendFile"); //True
        table1.Columns.Add("SendIM"); //False
        table1.Columns.Add("ReceiveIM"); //False
        table1.Columns.Add("ReplaceIM"); //False
        table1.Columns.Add("Windows"); //False
        table1.Columns.Add("MaxPacketRate"); //120
        table1.Columns.Add("UserProperties"); //False
        table1.Columns.Add("ClientVersion"); //6.0
        table1.Columns.Add("AppType"); //0
        table1.Columns.Add("Hidden"); //False

        table1.Rows.Add(
            7,
            "",
            "en-us",
            1,
            1,
            50,
            10,
            "File Sharing",
            "Share Files Between Two Users!",
            "http://appdirectory.messenger.msn.com/snake/index.html",
            "",
            0,
            "App",
            500,
            500,
            "side",
            2,
            2,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            120,
            false,
            6.0,
            0,
            false
            );

        DataSet ds = new DataSet(); //Create a dataSet with default (NewDataSet) name
        ds.Tables.Add(table1); //Add this table into our dataset


        //ds.ReadXml(@"MSGRP2P.xml");
        //return ((System.Data.DataSet)(results[0]));
        return (ds);
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/Messenger/Client/GetFilteredDataSet", RequestNamespace = "http://www.msn.com/webservices/Messenger/Client", ResponseNamespace = "http://www.msn.com/webservices/Messenger/Client", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]

    [WebMethod]
    public System.Data.DataSet GetFilteredDataSet(int LCID, int Page, int Kids, int AppType)
    {
        //object[] results = this.Invoke("GetFilteredDataSet", new object[] {
        //            LCID,
        //            Page,
        //            Kids,
        //            AppType});
        object[] results = new object[] {
                    LCID,
                    Page,
                    Kids,
                    AppType};
        return ((System.Data.DataSet)(results[0]));
    }


    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/Messenger/Client/GetFilteredDataSet2", RequestNamespace = "http://www.msn.com/webservices/Messenger/Client", ResponseNamespace = "http://www.msn.com/webservices/Messenger/Client", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]

    [WebMethod]
    public System.Data.DataSet GetFilteredDataSet2(string locale, int Page, int Kids, int AppType)
    {
        DataTable table1 = new DataTable("Entry");
        table1.Columns.Add("EntryID"); // 7
        table1.Columns.Add("Error"); //
        table1.Columns.Add("Locale"); //en-us
        table1.Columns.Add("Kids"); // 1
        table1.Columns.Add("Page"); // 1
        table1.Columns.Add("Category"); // 50
        table1.Columns.Add("Sequence"); // 10
        table1.Columns.Add("Name"); //File Sharing
        table1.Columns.Add("Description"); //Share Files Between Two Users!
        table1.Columns.Add("URL"); //http://appdirectory.messenger.msn.com/snake/index.html
        table1.Columns.Add("IconURL"); //
        table1.Columns.Add("PassportSiteID"); // 0
        table1.Columns.Add("Type"); //App
        table1.Columns.Add("Height"); //500
        table1.Columns.Add("Width"); //500
        table1.Columns.Add("Location"); //side
        table1.Columns.Add("MinUsers"); // 2
        table1.Columns.Add("MaxUsers"); // 2
        table1.Columns.Add("EnableIP"); //False
        table1.Columns.Add("ActiveX"); //True
        table1.Columns.Add("SendFile"); //True
        table1.Columns.Add("SendIM"); //False
        table1.Columns.Add("ReceiveIM"); //False
        table1.Columns.Add("ReplaceIM"); //False
        table1.Columns.Add("Windows"); //False
        table1.Columns.Add("MaxPacketRate"); //120
        table1.Columns.Add("UserProperties"); //False
        table1.Columns.Add("ClientVersion"); //6.0
        table1.Columns.Add("AppType"); //0
        table1.Columns.Add("Hidden"); //False

        table1.Rows.Add(
            1,
            "",
            "en-us",
            1,
            1,
            50,
            10,
            "File Sharing",
            "Share Files Between Two Users!",
            "http://appdirectory.messenger.msn.com/snake/index.html",
            "",
            0,
            "App",
            500,
            500,
            "side",
            2,
            2,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            120,
            false,
            6.0,
            0,
            false
            );

        DataSet ds = new DataSet(); //Create a dataSet with default (NewDataSet) name
        ds.Tables.Add(table1); //Add this table into our dataset


        //ds.ReadXml(@"MSGRP2P.xml");
        //return ((System.Data.DataSet)(results[0]));
        return (ds);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.msn.com/webservices/Messenger/Client")]
    public partial class Entry
    {

        private int entryIDField;

        private string errorField;

        private string localeField;

        private int kidsField;

        private int pageField;

        private int categoryIDField;

        private int sequenceField;

        private string nameField;

        private string descriptionField;

        private string uRLField;

        private string iconURLField;

        private string appIconURLField;

        private string typeField;

        private int heightField;

        private int widthField;

        private string locationField;

        private int minUsersField;

        private int maxUsersField;

        private int passportSiteIDField;

        private bool enableIPField;

        private bool activeXField;

        private bool sendFileField;

        private bool sendIMField;

        private bool receiveIMField;

        private bool replaceIMField;

        private bool windowsField;

        private int maxPacketRateField;

        private string logURLField;

        private bool userPropertiesField;

        private string subscriptionURLField;

        private string clientVersionField;

        private int appTypeField;

        private bool hiddenField;

        /// <remarks/>
        public int EntryID
        {
            get
            {
                return this.entryIDField;
            }
            set
            {
                this.entryIDField = value;
            }
        }

        /// <remarks/>
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        public string Locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }

        /// <remarks/>
        public int Kids
        {
            get
            {
                return this.kidsField;
            }
            set
            {
                this.kidsField = value;
            }
        }

        /// <remarks/>
        public int Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        public int CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }

        /// <remarks/>
        public int Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }

        /// <remarks/>
        public string IconURL
        {
            get
            {
                return this.iconURLField;
            }
            set
            {
                this.iconURLField = value;
            }
        }

        /// <remarks/>
        public string AppIconURL
        {
            get
            {
                return this.appIconURLField;
            }
            set
            {
                this.appIconURLField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public int Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public int MinUsers
        {
            get
            {
                return this.minUsersField;
            }
            set
            {
                this.minUsersField = value;
            }
        }

        /// <remarks/>
        public int MaxUsers
        {
            get
            {
                return this.maxUsersField;
            }
            set
            {
                this.maxUsersField = value;
            }
        }

        /// <remarks/>
        public int PassportSiteID
        {
            get
            {
                return this.passportSiteIDField;
            }
            set
            {
                this.passportSiteIDField = value;
            }
        }

        /// <remarks/>
        public bool EnableIP
        {
            get
            {
                return this.enableIPField;
            }
            set
            {
                this.enableIPField = value;
            }
        }

        /// <remarks/>
        public bool ActiveX
        {
            get
            {
                return this.activeXField;
            }
            set
            {
                this.activeXField = value;
            }
        }

        /// <remarks/>
        public bool SendFile
        {
            get
            {
                return this.sendFileField;
            }
            set
            {
                this.sendFileField = value;
            }
        }

        /// <remarks/>
        public bool SendIM
        {
            get
            {
                return this.sendIMField;
            }
            set
            {
                this.sendIMField = value;
            }
        }

        /// <remarks/>
        public bool ReceiveIM
        {
            get
            {
                return this.receiveIMField;
            }
            set
            {
                this.receiveIMField = value;
            }
        }

        /// <remarks/>
        public bool ReplaceIM
        {
            get
            {
                return this.replaceIMField;
            }
            set
            {
                this.replaceIMField = value;
            }
        }

        /// <remarks/>
        public bool Windows
        {
            get
            {
                return this.windowsField;
            }
            set
            {
                this.windowsField = value;
            }
        }

        /// <remarks/>
        public int MaxPacketRate
        {
            get
            {
                return this.maxPacketRateField;
            }
            set
            {
                this.maxPacketRateField = value;
            }
        }

        /// <remarks/>
        public string LogURL
        {
            get
            {
                return this.logURLField;
            }
            set
            {
                this.logURLField = value;
            }
        }

        /// <remarks/>
        public bool UserProperties
        {
            get
            {
                return this.userPropertiesField;
            }
            set
            {
                this.userPropertiesField = value;
            }
        }

        /// <remarks/>
        public string SubscriptionURL
        {
            get
            {
                return this.subscriptionURLField;
            }
            set
            {
                this.subscriptionURLField = value;
            }
        }

        /// <remarks/>
        public string ClientVersion
        {
            get
            {
                return this.clientVersionField;
            }
            set
            {
                this.clientVersionField = value;
            }
        }

        /// <remarks/>
        public int AppType
        {
            get
            {
                return this.appTypeField;
            }
            set
            {
                this.appTypeField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }
    }
}